version: "3.8"

services:
  mc:
    build: .
    ports:
      - 25565:25565
    environment:
      VIEW_DISTANCE: "20"
      EULA: "TRUE"
      MOTD: "A §l§cMinecraft§r §nserver"
      ONLINE_MODE: "FALSE"
      VERSION: 1.19
